# Generated by Django 2.2.1 on 2019-05-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=200)),
                ('order_type', models.CharField(max_length=200)),
                ('quantity', models.CharField(max_length=200)),
                ('currency', models.CharField(max_length=200)),
                ('exchange', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
